language: emacs-lisp

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el
env:
  - EMACS=emacs25
script:
  - emacs25 --version
  - $EMACS -batch -l pri.el
